// Which beaches share a model grid cell. Run by hand after the list of spots in
// core.js changes; the result is grid.js, which tools/inline.mjs copies into
// the page (this tool runs it at the end).
//
//   node tools/grid.mjs
//
// The models are coarser than the distance between beaches: 13 request points
// around Phuket fall into 3 to 6 cells, depending on the model. Open-Meteo
// counts every point of a request as a call, so the page asks for one point
// per cell and hands the answer to all the beaches in it. The numbers are the
// same as before, the request is a third of the size.
//
// A point is mapped to another one only when five days of every value the page
// reads are identical for the two. Points missing from grid.js are asked as
// they are, so a new beach works before this tool is run again.

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const OUT = path.join(ROOT, 'grid.js');
const UA = 'surf.voidstudio.top (github.com/Mihailchik/surf)';

const ctx = vm.createContext({ console });
vm.runInContext(fs.readFileSync(path.join(ROOT, 'core.js'), 'utf8') +
  '\n;globalThis.__core={ALL_SPOTS,WAVE_MODELS,WIND_MODELS,pointsOf};', ctx);
const C = ctx.__core;

async function jget(url) {
  for (let attempt = 1; ; attempt++) {
    try {
      const r = await fetch(url, { headers: { 'User-Agent': UA }, signal: AbortSignal.timeout(30000) });
      if (!r.ok) throw new Error('HTTP ' + r.status + ' ' + url.slice(0, 80));
      return [].concat(await r.json());
    } catch (e) {
      if (attempt >= 3) throw e;
      await new Promise(res => setTimeout(res, 5000 * attempt));
    }
  }
}

const { pts, base } = C.pointsOf(C.ALL_SPOTS, '&forecast_days=5');
const sig = (loc, keys) => keys.map(k => (loc.hourly[k] || []).join(',')).join('|');
// first point of each group of identical answers stands for the group
function group(sigs) {
  const first = {}, map = {};
  sigs.forEach((s, i) => { if (first[s] == null) first[s] = pts[i]; else map[pts[i]] = first[s]; });
  return map;
}

const WAVE = ['wave_height', 'wave_period', 'wave_direction', 'swell_wave_height', 'swell_wave_period', 'wind_wave_height'];
const WIND = ['wind_speed_10m', 'wind_direction_10m', 'wind_gusts_10m', 'precipitation'];
const SEA = ['sea_surface_temperature', 'sea_level_height_msl'];
const result = {};
for (const m of C.WAVE_MODELS) {
  const j = await jget('https://marine-api.open-meteo.com/v1/marine?' + base + '&hourly=' + WAVE.join(',') + '&models=' + m);
  result[m] = group(j.map(loc => sig(loc, WAVE)));
}
// one request serves all wind models, so a cell here is one that every model shares
const w = await jget('https://api.open-meteo.com/v1/forecast?' + base + '&hourly=' + WIND.join(',') +
  '&wind_speed_unit=ms&models=' + C.WIND_MODELS.join(','));
result.wind = group(w.map(loc => sig(loc, C.WIND_MODELS.flatMap(m => WIND.map(v => v + '_' + m)))));
const sea = await jget('https://marine-api.open-meteo.com/v1/marine?' + base + '&hourly=' + SEA.join(','));
result.sea = group(sea.map(loc => sig(loc, SEA)));

for (const [k, map] of Object.entries(result))
  console.log(k.padEnd(18), pts.length, 'points ->', pts.length - Object.keys(map).length, 'cells');
fs.writeFileSync(OUT, '/* Generated by tools/grid.mjs on ' + new Date().toISOString().slice(0, 10) + '. Do not edit by hand.\n' +
  '   Per source: request point -> the point that stands for its model grid cell.\n' +
  '   Points not listed stand for themselves. */\n' +
  'const GRID=' + JSON.stringify(result).replace(/"(\w+)":\{/g, '\n"$1":{') + ';\n');
console.log('written', OUT);
// index.html carries a copy of grid.js: refresh it right away
await import('./inline.mjs');
